version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-app
    container_name: backend-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-web
    container_name: frontend-web
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      # 以下の行を削除またはコメントアウト
      # - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cms
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=db
      - PMA_USER=myapp_user
      - PMA_PASSWORD=myapp_password
    depends_on:
      - db
    networks:
      - app-network

  nginx-webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
